### ISSUE TITLE
Assign to array indexes

### ISSUE THREAD

**Issue by FredTheDino** [FredTheDino/sylt-lang#117]
We currently don't support this syntax:
```
a := [1, 2, 3]
a[0] = 0
```
Do we want to?

**Comment by sornas** [comment]
I think yes, it's way too expected to be left out.

**Comment by FredTheDino** [comment]
So... Turns out this is like... Really complicated to do. I think we want to rewrite how we handle expressions.

**Comment by FredTheDino** [comment]
Doing an expression rewrite, for this case, to combine two branches into one.

**Comment by FredTheDino** [comment]
After thinking some more, the code is only duplicated 2 times. I don't like it but it simplifies a lot of other things in the compiler. That said, we should probably do a complete expression rewrite, since some of it is a bit convoluted. Like:
```
a! true <=> 0
```
Should in my mind work as a program. It might be a pipedream, and completely unnessecary. I don't know, one can argue that this code is a lot clearer and should be prefered
```
0 <=> a! true
```
I think this should morph into a new issue.

**Comment by sornas** [comment]
> I think this should morph into a new issue.

Sure. The question becomes if we have the time/energy for a complete rewrite.
