### ISSUE TITLE
Use files in subdirectories

### ISSUE THREAD

**Issue by sornas** [FredTheDino/sylt-lang#130]
```
use a/b

start :: fn {
  print b.c()
}
```

- [x] `use a/b` includes file `a/b.sy` under namespace b
- [x] `use a/b/c as y` includes file `a/b/c.sy` under namespace y
- [x] `use folder/` includes file `use folder/<something>.sy`
- [x] `use /a` includes `a.sy` in the project root (folder where main.sy is)

**Comment by FredTheDino** [comment]
We could also do the python route. Like:
```sylt
from a use b
print b.c()

use a.b
print b.c()
```
?

**Comment by sornas** [comment]
> `from a use b`

How would this work with a file `a/b/c.sy`?

> `use a.b`, `print b.c()`

I prefer this, but then we need a `use x as y` so we can resolve conflicts.

**Comment by sornas** [comment]
```
use a.b

a.b.c()
```

This conflicts with

```
use a

// a.sy
use b

// b.sy
c :: fn {}
```

so I agree with `a.b -> b.c()` as above.

**Comment by FredTheDino** [comment]
I agree with Pythons idea of not importing from the parent directory, but it might be overkill for this simple language, we could introduce a symbol that simply is "parent", like, idk, ".."? But it has to appear at the start.

I'm split, I kinda don't want it but it might save some time while developing.

**Comment by sornas** [comment]
I don't know about `..` since you'll only be able to import one step up. I say we skip it all together.

**Comment by EMattfolk** [comment]
Edvard and I had some ideas that we think would work well.

## Import a file
```
use file
file.foo()
```

## Import a folder
```
use folder/
folder.bar()
```

This would run a file in the folder with some name. Alternatives:

```
/folder/index.sy
/folder/init.sy
/folder/main.sy
/folder/load.sy
/folder/mod.sy
/folder/use.sy
/folder/_.sy
/folder/exports.sy
/folder/entry.sy
/folder/entry.sy
/folder/api.sy
/folder/public.sy
/folder/self.sy
```

## Import something specific

```
from file use spam

from folder/ use (
    stone,
)
```

## Renaming

```
use file as foo

from file use spam as eggs

from folder/ use (
    stone as hammer,
)
```

## Import from project root

Project root is where the main entry point is.

```
use /res/images/
```

**Comment by sornas** [comment]
Big :+1: for `/res/images/`
