### ISSUE TITLE
Better error enum

### ISSUE THREAD

**Issue by FredTheDino** [FredTheDino/sylt-lang#152]
I'm guessing you mean to have different error messages when checking/running so you can grep more easily, but I think the solution is actually to report the errors differently. I've been thinking of something like this:

```rust
pub enum Error {
    CompileError {
        kind: ErrorKind,
        file: Option<PathBuf>,
        line: Option<usize>,
        message: Option<String>,
    },
    TypecheckError {
        kind: ErrorKind,
        file: PathBuf,
        line: usize,
        message: Option<String>,
    },
    RuntimeError {
        kind: ErrorKind,
        file: PathBuf,
        line: usize,
        message: Option<String>,
    },
    BincodeError,
}
```

We'd have to change some things in our test files, but that may be for the better since we'd have to specify *when* an error should be found. We don't want to miss when a type error used to be found during type checking but is suddenly only found in the runtime.

_Originally posted by @sornas in https://github.com/FredTheDino/sylt-lang/pull/146#discussion_r601182866_

**Comment by sornas** [comment]
#162
