### ISSUE TITLE
Move out lingon?

### ISSUE THREAD

**Issue by FredTheDino** [FredTheDino/sylt-lang#158]
Should Lingon live in this repo? Or should it be another repo?

**Comment by FredTheDino** [comment]
I'm starting to think we should

**Comment by sornas** [comment]
:+1:

**Comment by sornas** [comment]
Maybe even a github org??? `sylt/sylt-lang` and `sylt/lingon`.

**Comment by FredTheDino** [comment]
lingon isn't part of sylt-lang, I don't like the grouping.
