### ISSUE TITLE
Constructors/Initalizers

### ISSUE THREAD

**Issue by FredTheDino** [FredTheDino/sylt-lang#16]
Or something constructor like. It's noisy and slow to initialize blobs. It would be nice if it could be done more cleanly.

Maybe syntax like:
```
blob A (a: int) {
    a: int = a
    f := fn b: int -> int {
        ret b + 1
    }
}
```

**Comment by FredTheDino** [comment]
Thinking of skipping this, and just forcing people to make a function for it instead. Removes complexity from the language, I don't know if this is needed.

**Comment by sornas** [comment]
Agree

**Comment by FredTheDino** [comment]
This is "fixed". The initalizer syntax changed a bit but it should be smooth now!
#171
