### ISSUE TITLE
Lisp-y dialect?

### ISSUE THREAD

**Issue by sornas** [FredTheDino/sylt-lang#217]
We considered something like the following

```
(fn f (n: int -> int)
 (:= a (+ n 1))
 (:= b (+ a n))
 (ret (* a b)))
```
or
```
(fn f (n: int -> int)
 (let a (+ n 1))
 (let b (+ a n))
 (* a b))
```
or
```
f :: fn n: int -> int {
  (let a (+ n 1))
  (let b (+ a n))
  (* a b)
}
```
I'm partial towards `(fn )`-declarations since it matches with the rest (having `fn` be "read" as a function).

What about `(type n: int -> int)` so `type` is a special function that has another syntax? Otherwise it's kinda arbitrary when a type-expression is expected. That way we could also have types as values more clearly, compared to the current in-between. So:

```
(fn f (type n: int -> int)
 (let a (+ n 1))
 (let b (+ a n))
 (* a b))
```

There's many discussions about style to have here. I just wanted to write down what we said today.

**Comment by FredTheDino** [comment]
After more discussion and reflection. I think we've reached the conclusion that the lisp syntax won't give us anything we don't have. It won't solve a problem other than an implementation complexity problem, which can be solved in a different way.

See #218
