### ISSUE TITLE
Iterator replacement

### ISSUE THREAD

**Issue by FredTheDino** [FredTheDino/sylt-lang#272]
- [x] for_each
- [x] map
- [ ] reduce (#398)
- [ ] fold (#398)
- [x] filter

**Comment by FredTheDino** [comment]
- for_each
 - map
 - reduce
 - filter

**Comment by EMattfolk** [comment]
I think it is better to have fold instead of reduce. It is more general and handles empty collections very well.

**Comment by sornas** [comment]
Por que no los dos?
