### ISSUE TITLE
Assign to index in tuple

### ISSUE THREAD

**Issue by FredTheDino** [FredTheDino/sylt-lang#285]
FredTheDino/PuckNet@e08f449f42

**Comment by FredTheDino** [comment]
I don't think this issue makes sense. It is a tuple - which is immutable and that's kinda the point.

So this is not a bug - it's a feature.

Gonna close tomarrow unless someone tries to stop me. @sornas @EMattfolk

**Comment by sornas** [comment]
Agreed
