### ISSUE TITLE
Git conflict marker spans looks off by one

### ISSUE THREAD

**Issue by sornas** [FredTheDino/sylt-lang#294]

**Comment by sornas** [comment]
The source has been lost to the git gods. Hopefully it's reproducible.

**Comment by FredTheDino** [comment]
I failed to reproduce this using this very simple example. But it doesn't look off-by one. Closing tomorrow if nothing new is added.
```
start :: fn {
>>>>>>>
    print "A"
=======
    print "B"
<<<<<<<
}

// Gives

git conflict error: hello.sy:6
      Git conflict marker found at line 6
   4 | =======
   5 |     print "B"
   6 | <<<<<<<
      ^^^^^^^

```

**Comment by sornas** [comment]
No that is the problem. The `^^^^^^^` should be one cell to the right.
