### ISSUE TITLE
Typecheck panic when using (modifying?) a global from another file

### ISSUE THREAD

**Issue by sornas** [FredTheDino/sylt-lang#306]
See https://github.com/FredTheDino/PuckNet/commit/5d6523a15ca323cc90cb6024a31c340dc69f58b3 for workaround.

**Comment by FredTheDino** [comment]
Failed to reproduce - closing tomarrow if nothing new is added.

**Comment by sornas** [comment]
[This commit](https://github.com/FredTheDino/PuckNet/commit/4274b8bb83ef1d2780db9406507ebbb0e978f668) (applied on top of the commit linked above) causes the following panic:

```
thread 'main' panicked at 'index out of bounds: the len is 2 but the index is 2', sylt/sylt-typechecker/src/typechecker.rs:371:26
```
