### ISSUE TITLE
Immediate calling of functions

### ISSUE THREAD

**Issue by EMattfolk** [FredTheDino/sylt-lang#336]
In #331 support for immediate indexing, accessing and calling functions was added, however, it is still not possible to do things like:

```
fn -> int { 2 }()
// or
fn -> int { 2 }'
```

Should this be fixed? Because it is still possible to call the functions if they are wrapped in parenthesis like this:

```
(fn -> int { 2 })()
```

**Comment by sornas** [comment]
I think it's a cool construct to support, especially if we already support the wrapped version.
