### ISSUE TITLE
Invalid program: `start :: {}`

### ISSUE THREAD

**Issue by EMattfolk** [FredTheDino/sylt-lang#348]
```
start :: {}
```

**Comment by EMattfolk** [comment]
Is this something to fix? It happened because I forgot to write "fn".

**Comment by sornas** [comment]
Yeah I think so. It should be the same error as when not supplying a `start` at all.

**Comment by FredTheDino** [comment]
The error I get is:
```
typecheck error: hello.sy:0
      [!!] Invalid program [!!]
Failed to call

Error: "1 errors occured."
```
Which is a decent error - but it's a typechecking problem, so hold off on it until the new typechecker is done.

**Comment by sornas** [comment]
For something actionable, I think it should in some way point to the fact that `start` should be a function and not a set (dict?).

**Comment by FredTheDino** [comment]
We don't have that information in the current typechecker. All it knows is that you tried to call something that it has no idea how to call. Variablenames have been lost a long time ago.

In other words - making this error better, is a lot of work. Unless you have a typechecker that works on the AST. But I'm not sure where your timehorizon for `actionable` is.
