### ISSUE TITLE
Problem passing external functions as arguments

### ISSUE THREAD

**Issue by FredTheDino** [FredTheDino/sylt-lang#361]
This causes a wierd problem on the tree-typechecker branch
```
for_each([1, 2, 3], print)
```
but this works:
```
for_each([1, 2, 3], fn x:int -> void { print(x) })
```

**Comment by sornas** [comment]
https://github.com/FredTheDino/sylt-lang/blob/1b1ff2215069d9395e9fe23ceaa71b5b3bd28e47/sylt-machine/src/vm.rs#L127 panics on the `unwrap`.

**Comment by sornas** [comment]
Also fails on main so not related to the typechecker.
