### ISSUE TITLE
Syntax for namespaces

### ISSUE THREAD

**Issue by FredTheDino** [FredTheDino/sylt-lang#407]
We need some syntax to create local namespaces. Maybe something like:
```
namespace abc
	...
end
```
(I mean why over complicate this?)
This would be usefull in the lua-compiler, if we want to add love-bindings, since it's kinda namespaced.

**Comment by EMattfolk** [comment]
I would say either
```
abc :: namespace do
    ...
end
```
or
```
abc :: namespace {
    ...
}
```
It would be more in line with the language as it is currently.

**Comment by FredTheDino** [comment]
Unclear if this is needed or not.
