### ISSUE TITLE
Double negation

### ISSUE THREAD

**Issue by EMattfolk** [FredTheDino/sylt-lang#426]
This program does not work
```
start :: fn do
    1--1     <=>  2
    1        <=>  1
    -1       <=> -1
    --1      <=>  1
    ---1     <=> -1
    ----1    <=>  1
    -----1   <=> -1
    ------1  <=>  1
    -------1 <=> -1
end
```
I think it is fine if it doesn't, but the error message should be clearer.
I believe the problem lies with the tokens `--` and `++`.

**Comment by FredTheDino** [comment]
What is the error you get and what error would you like to get?

**Comment by sornas** [comment]
I would honestly be fine with not having -- and ++ as tokens and allow the
program as written. +=/-= 1 is a good enough replacement.

**Comment by FredTheDino** [comment]
But it does feel a bit esoteric to write this many minussigns - I'm not sure it's communicating some valid intent. We don't have for-loops, which feels like the prime use-case for `++`, so just removing `--` might be the best option.
